name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logo/swach.jpg
    - assets/uploads/1.jpg
    - assets/uploads/2.jpg
    - assets/uploads/3.jpg
    - assets/uploads/4.jpeg
    - assets/uploads/5.jpeg
    - assets/uploads/6.jpeg
